name: hello-from-R
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-from-bash
        run: echo "Hello from Bash!"

      - name: checkout-repo
        uses: actions/checkout@v3

      - name: install-r
        uses: r-lib/actions/setup-r@v2

